In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
def softmax(x):
    x = np.array(x)
    exp_x = np.exp(x-np.max(x))
    return exp_x/np.sum(exp_x)

def cce(y_true,y_pred):
    y_pred = np.clip(y_pred,1e-12,1-1e-12)
    return -np.sum(y_true*np.log(y_pred))/y_true.shape[0]

def cced(y_true, y_pred):
    return y_pred-y_true

def forward(X,weights):
    return softmax(np.dot(X,weights))

def backward(X, y_true, y_pred, lr):
    grad = cced(y_true, y_pred)
    dw = np.dot(X.T,grad)/X.shape[0]
    return dw*lr

In [16]:
X = np.array([[1.0,2.0],[1.5,2.5],[2.0,3.0]])
weights = np.array([[0.2,-0.3,0.5],[-0.3,0.2,0.7]])
y_true = np.array([[1,0,0],[0,1,0],[0,0,1]])

y_pred = forward(X,weights)
loss = cce(y_true, y_pred)
print(y_pred)
print(loss)
print(backward(X,y_true,y_pred,0.01))

[[0.01452882 0.02395398 0.14491312]
 [0.01382024 0.02278573 0.26404892]
 [0.01314622 0.02167446 0.48112851]]
2.914954211889933
[[-0.00312816 -0.00466173 -0.00165585]
 [-0.00632318 -0.00776701 -0.00202222]]
