In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def softmax(x):
    x = np.array(x)
    exp_x = np.exp(x-np.max(x))
    return exp_x/np.sum(exp_x)

def cce(y_true,y_pred):
    y_pred = np.clip(y_pred,1e-12, 1-1e-12)
    return -np.sum(y_true*np.log(y_pred))/y_true.shape[0]
def cced(y_true,y_pred):
    return y_pred-y_true
def forward(X,weights):
    y_pred = softmax(np.dot(X,weights))
    return y_pred
def backward(X,y_true,y_pred,lr):
    grad = cced(y_true,y_pred)
    dw = np.dot(X.T,grad)/X.shape[0]
    return dw*lr

In [6]:
X = np.array([[1.0,2.0],[1.5,2.5],[2.0,3.0]])
weights = np.array([[0.2,-0.3,0.5],[-0.5,0.7,-0.2]])
y_true = np.array([[0,1,0],[1,0,0],[0,0,1]])

y_pred = forward(X,weights)
loss = cce(y_true,y_pred)
print(y_pred)
print(loss)
print(backward(X,y_true,y_pred,0.01))

[[0.0277276  0.18538383 0.0681989 ]
 [0.02386537 0.22642832 0.07923582]
 [0.02054111 0.27656017 0.09205888]]
2.601993529806192
[[-0.00465131  0.00026049 -0.00542943]
 [-0.00774419 -0.00077827 -0.00796445]]
